# Generated by Django 3.0.7 on 2020-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('size', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'farm')])),
                ('area', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('cars', models.FloatField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
