# Generated by Django 3.0.7 on 2020-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.IntegerField(choices=[(1, 'Farm')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
