# Generated by Django 3.0.7 on 2020-06-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20200628_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='rated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='rating',
            field=models.FloatField(default=0.5),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='homes.Home')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='homes.Home')),
            ],
        ),
    ]
