# Generated by Django 3.0.7 on 2020-06-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_remove_match_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('winner', 'loser')},
        ),
    ]
