# Generated by Django 3.0.7 on 2020-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20200628_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
