# Generated by Django 3.0.7 on 2020-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_home_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
