# Generated by Django 3.0.7 on 2020-08-11 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_auto_20200811_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
