# Generated by Django 3.0.7 on 2020-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20200811_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
